### ISSUE TITLE
does not compile with gcc 4.0.1 error: invalid lvalue in assignment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w8tvi/dircproxy#39]
```
me and gcc 4.0.1 are not able to parse this:
{{{
 s = (l ? l->next : p->squelch_modes) = n;

irc_server.c:788: error: invalid lvalue in assignment
irc_server.c:829: error: invalid lvalue in assignment
make[2]: *** [irc_server.o] Error 1
}}}


```

Original issue reported on code.google.com by `noel.w8tvi` on 29 Sep 2008 at 5:47
